### ISSUE TITLE
Recipes with the same prefix（roasted mutton chops and shepherds pies）

### ISSUE THREAD

**Issue by FunMelon** [Flomik10002/DelightfulCreatorsFabric#13]
Both the recipes of the roasted mutton chops and the shepherds pies are started with empty bowl and cooked mutton. And when I try to assemble the roasted mutton chops, only I can get are the incomplete shepherds pies. Do all the recipes in this mod need to be unique in the first step？
My game version is 1.19 and my mod version is 1.1.7 fabric. 
By the way, I both install this mod and the slice & dice, for the reason that the latter supports recipes in other delight  mod. But I really don‘t like finish all task in only one pot, which is ugly and loses the beauty of the create.
![image](https://github.com/Flomik10002/DelightfulCreatorsFabric/assets/96934158/5029c7d9-3c9c-4237-952f-4adff670bdec)
![image](https://github.com/Flomik10002/DelightfulCreatorsFabric/assets/96934158/a1894556-c2c6-4473-b0c9-645704f16508)

**Comment by Flomik10002** [comment]
I fixed it. Thanks for describing the error, you can download the new version in the release on Github. Will appear on Curseforge later
