### ISSUE TITLE
[Compat] Compatibility with Farmer's Delight Refabricated [Fabric 1.20.1]

### ISSUE THREAD

**Issue by NolanHewitt** [Flomik10002/DelightfulCreatorsFabric#14]
Compatibility for the new Farmer's Delight port:

https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated?

It offers more support for a better port which is more faithful to the original mod on Forge, and is cleaner internally and has less bugs.

**Comment by suerion** [comment]
@Flomik10002 Farmers Delight Refabricated is not a Port anymore, it is the official Farmers Delight, please Update the Compatibility to the New Refabricated version.

Thanks a lot

**Comment by bangetto** [comment]
the old fabric version of FD has ben deprecated

**Comment by Flomik10002** [comment]
> @Flomik10002 Farmers Delight Refabricated is not a Port anymore, it is the official Farmers Delight, please Update the Compatibility to the New Refabricated version.
> 
> Thanks a lot

Finally I made full support for the refabricated mod

**Comment by Flomik10002** [comment]
> the old fabric version of FD has ben deprecated

Finally I made full support for the refabricated mod

**Comment by Flomik10002** [comment]
> Compatibility for the new Farmer's Delight port:
> 
> https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated?
> 
> It offers more support for a better port which is more faithful to the original mod on Forge, and is cleaner internally and has less bugs.

Finally I made full support for the refabricated mod
