### ISSUE TITLE
Отсутствующие крафты, непонятные названия, отсутствие документации, неработающие ссылки

### ISSUE THREAD

**Issue by RushanM** [Flomik10002/DelightfulCreatorsFabric#15]
У еды из мода нет крафтов? EMI показывает крафт только «Неполного блюда из макарон». И почему эти блюда называются «неполными»? Как тогда сделать полное? И почему ради того, чтобы просто положить пасту на миску, я должен использовать какую-то машину из Create, а не просто слоты крафта в инвентаре?

Что вообще должно значить название мода «Восхитительные создатели»? Я понимаю, что это должен быть каламбур между Create и Farmer's Delight, но звучит вообще не очень... К тому же не вижу, как это название может отражать назначение мода.

Пожалуйста, сделайте вики по моду, где всё будет разъяснено, разжёвано, ибо я особо не понимаю, зачем это всё сделано. К тому же в моде есть какие-то достижения, а как их получить тоже непонятно, пока сам не полезешь в код мода и не посмотришь, что тебе для этого нужно.

Ссылки на Модринт в этом репозитории ведут на неработающую ссылку. Прошу это исправить.

**Comment by Flomik10002** [comment]
Мужик, обрати внимание, что мой мод НЕ ДОБАВЛЯЕТ НОВУЮ ЕДУ. Мод добавляет крафты для еды из FARMERS DELIGHT С ПОМОЩЬЮ МОДА CREATE. Предметы в моем моде НЕ НУЖДАЮТСЯ в крафте ибо они являются переходным предметом крафта последовательной сборки. Поддержку мода для modrinth я прекратил в силу неудобства. Подобную критику можете оставить для своих проектов ;)
