### ISSUE TITLE
Poor compatibility with the Sinytra Connector (I doubt this is your problem, however you yourself asked me to post this)

### ISSUE THREAD

**Issue by avehavens** [Flomik10002/DelightfulCreatorsFabric#18]
Tested everything on version 1.20.1 on Forge version 47.3.0.

List of mods:
FarmersDelight-1.20.1-1.2.4
create-1.20.1-0.5.1.f
Connector-1.0.0-beta.44+1.20.1
ConnectorExtras-1.11.2+1.20.1
fabric-api-0.92.2+1.11.8+1.20.1
jei-1.20.1-forge-15.8.0.14
delightful-creators-1.3-1.20.x

One of the main problems is Farmer`s Delight tags, I attached some recipes on my own.

![image](https://github.com/user-attachments/assets/98aa99e2-55f6-47e0-8760-6905cb342b3b)
![image](https://github.com/user-attachments/assets/3d5ee03f-c07f-4cc1-9e60-ca54f7d161c7)
![image](https://github.com/user-attachments/assets/340adf7d-f138-4db1-9183-5c528cc45fb6)

However, there is a worse problem and it is related to the Create mod. When going into some recipes through JEI and going into the sequential mechanism, minecraft crashes. (I noticed this when going into the Shepherd's Pie recipe).

[crash-2024-07-19_16.14.50-client.txt](https://github.com/user-attachments/files/16311228/crash-2024-07-19_16.14.50-client.txt)

- I apologize for my English, I translated the text through Deepl translator.

**Comment by Flomik10002** [comment]
I believe that you need to send this issue in the issues tracker of Sinytra. As I understand they asked people to send them crashes with different mods. Try to write them, cause I don't know how I can fix it.

**Comment by avehavens** [comment]
Okey!
