### ISSUE TITLE
Some fluid recipies not displaying in JEI and its counterparts properly

### ISSUE THREAD

**Issue by Hyperbuss** [Flomik10002/DelightfulCreatorsFabric#21]
Despite requiring beef, the stew only shows 2 of the three ingredients
![image](https://github.com/user-attachments/assets/f491a7ef-0399-43f3-8925-5f247eb8397e)

Fish stew example
![image](https://github.com/user-attachments/assets/e5bcdf19-ff80-4211-b949-cec4e75a1371)

Pumpkin Soup
![image](https://github.com/user-attachments/assets/6b634d67-08a9-4142-a45d-0ecd9ac4f5ae)

I initially found this in EMI, treid switching to JEI and the problem persisted

**Comment by Flomik10002** [comment]
Do you have another recipes for each of these recipes?

**Comment by Hyperbuss** [comment]
the recipes in question have 2 mixing pages and the second page includes the missing food.
![image](https://github.com/user-attachments/assets/bd4e913b-8ad4-45d8-b18d-0c4448a5d994)
