### ISSUE TITLE
Invalid items in recipes (and also duplicate ones with FD Refabricated)

### ISSUE THREAD

**Issue by bangetto** [Flomik10002/DelightfulCreatorsFabric#22]
![2024-08-24_20 31 27](https://github.com/user-attachments/assets/59d79ebf-3ec8-4b23-8080-85fa4b4191c9)
![2024-08-24_20 33 00](https://github.com/user-attachments/assets/bf295d7d-05c8-427e-9380-a48ff31695d8)
![2024-08-24_20 33 15](https://github.com/user-attachments/assets/9cbafbe7-53eb-40d9-8a6e-9d5413e71933)
![2024-08-24_20 33 27](https://github.com/user-attachments/assets/db7b0289-d716-42b3-8e61-2ea89a02e75d)
![2024-08-24_20 33 43](https://github.com/user-attachments/assets/2bdc7cbd-0d6b-4e50-aa46-ce2a7de79084)
![2024-08-24_20 33 52](https://github.com/user-attachments/assets/b0eaa606-495c-4c16-88d3-4ed6fd3f8c12)
![2024-08-24_20 34 14](https://github.com/user-attachments/assets/52d7988f-c0a0-4627-9ecc-7bffbf8de05a)
![2024-08-24_20 29 27](https://github.com/user-attachments/assets/b9336720-2607-4d17-88a9-5229252c55c8)
![2024-08-24_20 29 58](https://github.com/user-attachments/assets/9b525ee7-8933-4f3d-86da-0a1af176e2a0)
![2024-08-24_20 30 16](https://github.com/user-attachments/assets/f842ea9e-2d54-4426-a4b5-545827d2b562)
![2024-08-24_20 30 41](https://github.com/user-attachments/assets/899603ad-83a9-4ace-9c00-6e64695ad29a)
![2024-08-24_20 31 04](https://github.com/user-attachments/assets/da702573-802e-4083-9a5a-5193d986d3cb)

the list of duplicates is longer

**Comment by GE0fr** [comment]
Same problem here ! 
And i noticed that the second recipe (1st image) broke after a server reload, it was showing items before and now it is also invalid 

![image](https://github.com/user-attachments/assets/87167b3c-a035-497f-9f20-cef8ff23a0d6)
![image](https://github.com/user-attachments/assets/3b0cb74c-ba65-4024-bdcf-31815542b7fd)

**Comment by bangetto** [comment]
I found the root of the problem for the duplicate ones
![image](https://github.com/user-attachments/assets/0a8e9533-2dde-478b-81f9-e07a54ad7d19)
this is unnecessary
