### ISSUE TITLE
[feature request] adding a way to cut stuff with create automation

### ISSUE THREAD

**Issue by koppiki** [Flomik10002/DelightfulCreatorsFabric#6]
I like this project a lot more than slice and dice, but one thing I do miss is the ability to automate the cutting of stuff in a create production line. Could you add a way to do that (or if there is, what is it)? I know I could just install slice and dice in parallel with it, but I'd rather avoid the other stuff that mod adds.

Thank you for your consideration.

**Comment by Flomik10002** [comment]
I apologize for such a long wait, along the way I am developing two similar mods. I thought about how this can be done and I think that I can write something similar to Slice and Dice 😄

**Comment by axd1x8a** [comment]
This is not necessary, you can use funnels and deployers with cutting board and make a setup like this, that prevents deployer from putting knife on it
![image](https://github.com/Flomik10002/DelightfulCreatorsFabric/assets/26704473/8c820494-87e2-420b-87a6-eb1273a0375d)
