### ISSUE TITLE
Recipe Problems

### ISSUE THREAD

**Issue by Peatral** [Flomik10002/DelightfulCreatorsFabric#7]
When crafting the Honey Glazed Ham or Steak and Potatoes, you usually get the bowl back one has used to craft the cooked rice. In contrary, when crafting those recipes using the recipe sequences you just lose the bowl. I think this should be avoided, for example by placing the cooked rice at the beginning instead of the empty bowl. I think these are the only two recipes but I don't know if I missed something.

I also realized that for example the Stuffed Pumpkin usually gets cooked using the Cooking Pot but this also is ignored in the Recipe Sequence. Maybe one could add bulk smoking as a last step (although I am not sure if this is possible as no other recipe does that afaik, and I haven't taken a look at the recipe sequence code myself).

Besides these two things, there are 11 missing recipes which can't be automated using recipe sequences or heated mixing (If I counted correctly).
Those recipes are:
- Dumplings
- Cabbage Rolls
- Cooked Rice
- Bone Broth
- Fired Rice
- Baked Cod Stew
- Mushroom Rice
- Vegetable Noodles
- Ratatouille
- Squid Ink Pasta
- Dog Food

I am currently adding those recipes as simple heated mixing recipes with kubejs, but a real implementation (heated mixing or recipe sequence) would of course be better. Fixing the first two problems with kubejs feels quite janky as I would have to modify (replace?) existing recipe sequences, I definitly don't know to which degree that is possible (and should be ideally not need when they are fixed).

Besides these things I very much prefer this mod over slice and dice (not because of the other stuff it adds but because all of the fluid this one adds, it is just way more interesting), although I currently have to use both to a certain degree as there is currently no way to automate cutting with this mod, but I have seen there is already another issue opened for that. 

All in all, it would be really nice if all of the above could be fixed/added somehow.

**Comment by Flomik10002** [comment]
> to use both to a certain degree as there is currently no way to automate cutting with this

Okay, I heard your point. I will think about it and think in the next update I will implement it

**Comment by Peatral** [comment]
Although the automation of cutting, log stripping, etc. is an issue, I personally think it's a minor one (as you can just use slice and dice atm till its implemented). But I think it's still important to consider how to set this apart from Slice and Dice (maybe make the block more like the saw or the chisel from rechiseled create).

To me personally the other issues are more important, especially the rice bowl situation as resources just vanish into thin air. The missing recipes are also nothing small to overlook, the heating in recipe sequences in contrary is just me being petty lol.

**Comment by Flomik10002** [comment]
Heating in recipe sequences is not possible as far as I know. I will fix your problems in the release for 1.20.1, and then for 1.19.2, because at the moment it is not convenient
