### ISSUE TITLE
Pasta Recipes sharing assembly sequence

### ISSUE THREAD

**Issue by Polaris277** [Flomik10002/DelightfulCreatorsFabric#8]
# Issue Description
Currently both pasta with meatballs and pasta with button share the first step of deploying pasta into a bowl, however this will always create incomplete mutton pasta.
| Meatballs | Mutton |
|-----------|--------|
|    <img width="455" alt="image" src="https://github.com/Flomik10002/DelightfulCreatorsFabric/assets/146779608/d1d866c4-027a-4e94-b07d-955b0bbb1307">       |     <img width="493" alt="image" src="https://github.com/Flomik10002/DelightfulCreatorsFabric/assets/146779608/69b43be3-c9a2-471c-9b0d-515190e2ff9e">   |

Attempting to use a cooked beef patty on an incomplete mutton pasta will cause the deployer to not run rendering the creation of pasta with meatballs impossible

# Mod Versions
Minecraft: 1.19.2
Fabric: 0.14.22
Delightful Creators: 1.1.7
Create: 0.5.1-b
Farmers Delight: 1.19.2-1.3.10.1

**Comment by Flomik10002** [comment]
Thanks for the information, if I understood the problem correctly, then it has already been fixed and the version of the mod with the fix has already been uploaded to the sites and is under moderation

**Comment by Polaris277** [comment]
Just retried with the newest version on curseforge (Uploaded Oct 03 2023) and still seeing this issue
